support global redefinition in solver test installation

diff --git a/test/test_solvers b/test/test_solvers
--- a/test/test_solvers
+++ b/test/test_solvers
@@ -22,6 +22,7 @@ do
     solver=`basename $s`
     echo "Found solver $solver"
     
+    SOLVER_DIR="$SUNNY_HOME/solvers/$solver"    
     MZNLIB=""
     STDLIB=""
     
@@ -30,7 +31,7 @@ do
       echo "mznlib global definiton detected"
     fi
     
-    if [ -d "$SOLVER_DIR/stdlib" ]; then
+    if [ -d "$SOLVER_DIR/std-lib" ]; then
       STDLIB="-I $SOLVER_DIR/stdlib"
       echo "stdlib global definiton detected"
     fi
@@ -50,7 +51,7 @@ do
       if 
 	[ $ret -ne 0 ]
       then
-	echo "Error in lunching $solver (return error $ret)" 1>&2
+	echo "Error in launching $solver (return error $ret)" 1>&2
       else
 	echo "Parsing the output"
 	solns2out $OZN $OUT &> /dev/null
@@ -60,7 +61,7 @@ do
 	then
 	  echo "Error in parsing $solver output (return error $ret)" 1>&2
 	else
-	  echo "$s passed the CP test"
+	  echo "$solver passed the CP test"
 	fi
       fi
     fi
