Rewrote schedule parallelization and dynamic solving.

diff --git a/test/examples/run_examples b/test/examples/run_examples
--- a/test/examples/run_examples
+++ b/test/examples/run_examples
@@ -5,6 +5,7 @@ IN_PATH=$SUNNY_HOME/test/examples
 OZN=$IN_PATH/tmp.ozn
 OUT=$IN_PATH/out
 ERR=$IN_PATH/err
+CORES=2
 TIMEOUT=10
 OUTPUT=$IN_PATH/output.log
 ERRORS=$IN_PATH/errors.log
@@ -20,7 +21,7 @@ do
     for d in domino.1.dzn domino.2.dzn
     do
       mzn2fzn $m $d --output-ozn-to-file $OZN
-      cmd="sunny-cp -T $TIMEOUT --g12 $m $d"
+      cmd="timeout $TIMEOUT sunny-cp -p $CORES -T $TIMEOUT --g12 $m $d"
       $cmd 1>$OUT 2>$ERR
       ret=$?
       cat $OUT | solns2out $OZN | solns2dzn -l
@@ -29,16 +30,23 @@ do
       cat $OUT >> $OUTPUT
       cat $ERR >> $ERRORS
       if
-	[ $ret -ne 0 ]
+        [ $ret -ne 0 ]
       then
-	echo "Error while solving $m!!! Test aborted."
-	echo "Have a look at the log files $OUTPUT and $ERRORS"
-	exit $ret
+        if
+          [ $ret -eq 124 ]
+        then
+          echo "Timeout while solving $m!!!"
+        else
+	  echo "Error while solving $m!!! Test aborted."
+	  echo "Have a look at the log files $OUTPUT and $ERRORS"
+	  rm *.fzn
+	  exit $ret
+        fi
       fi
     done
   else
     mzn2fzn $m --output-ozn-to-file $OZN
-    cmd="sunny-cp -T $TIMEOUT --g12 $m"
+    cmd="timeout $TIMEOUT sunny-cp -p $CORES -T $TIMEOUT --g12 $m"
     $cmd 1>$OUT 2>$ERR
     ret=$?
     cat $OUT | solns2out $OZN | solns2dzn -l
@@ -49,10 +57,16 @@ do
     if
       [ $ret -ne 0 ]
     then
-      echo "Error while solving $m!!! Test aborted."
-      echo "Have a look at the log files $OUTPUT and $ERRORS"
-      rm *.fzn
-      exit $ret
+      if
+        [ $ret -eq 124 ]
+      then
+        echo "Timeout while solving $m!!!"
+      else
+	echo "Error while solving $m!!! Test aborted."
+	echo "Have a look at the log files $OUTPUT and $ERRORS"
+	rm *.fzn
+	exit $ret
+      fi
     fi
   fi
   echo "$m processed!"
