Fixed bugs. Now all the examples in test/examples pass.

diff --git a/test/examples/run_examples b/test/examples/run_examples
--- a/test/examples/run_examples
+++ b/test/examples/run_examples
@@ -3,10 +3,16 @@
 
 IN_PATH=$SUNNY_HOME/test/examples
 OZN=$IN_PATH/tmp.ozn
-PFOLIO='g12cbc,g12cpx,g12fd,g12lazyfd'
+PFOLIO='g12cpx,g12lazyfd,g12fd,g12cbc'
 BACKUP='g12cpx'
-PROC=1
+PROC=4
+OUT=$IN_PATH/out
+ERR=$IN_PATH/err
+TIMEOUT=10
+OUTPUT=$IN_PATH/output.log
+ERRORS=$IN_PATH/errors.log
 cd $IN_PATH
+rm $OUTPUT $ERRORS 2>/dev/null
 
 for m in `ls *.mzn`
 do
@@ -16,32 +22,46 @@ do
   then
     for d in domino.1.dzn domino.2.dzn
     do
-       mzn2fzn $m $d --output-ozn-to-file $OZN
-       echo "$PFOLIO" "$BACKUP"
-       sunny-cp -p "$PROC" -P "$PFOLIO" -b "$BACKUP" -T 30 $m $d | solns2out $OZN | solns2dzn -l
-       ret=$?
-       if
-         [ $ret -ne 0 ]
-       then
-         echo "Error while solving $m!!! Test aborted."
-         exit $ret
-       fi
+      mzn2fzn $m $d --output-ozn-to-file $OZN
+      cmd="sunny-cp -p $PROC -P $PFOLIO -b $BACKUP -T $TIMEOUT $m $d"
+      $cmd 1>$OUT 2>$ERR
+      ret=$?
+      cat $OUT | solns2out $OZN | solns2dzn -l
+      echo '********** Instance: '$cmd >> $OUTPUT
+      echo '********** Instance: '$cmd >> $ERRORS
+      cat $OUT >> $OUTPUT
+      cat $ERR >> $ERRORS
+      if
+	[ $ret -ne 0 ]
+      then
+	echo "Error while solving $m!!! Test aborted."
+	echo "Have a look at the log files $OUTPUT and $ERRORS"
+	exit $ret
+      fi
     done
   else
     mzn2fzn $m --output-ozn-to-file $OZN
-    sunny-cp -p "$PROC" -P "$PFOLIO" -b "$BACKUP" -T 30 $m | solns2out $OZN | solns2dzn -l
+    cmd="sunny-cp -p $PROC -P $PFOLIO -b $BACKUP -T $TIMEOUT $m"
+    $cmd 1>$OUT 2>$ERR
     ret=$?
+    cat $OUT | solns2out $OZN | solns2dzn -l
+    echo '********** Instance: '$cmd >> $OUTPUT
+    echo '********** Instance: '$cmd >> $ERRORS
+    cat $OUT >> $OUTPUT
+    cat $ERR >> $ERRORS
     if
       [ $ret -ne 0 ]
     then
       echo "Error while solving $m!!! Test aborted."
+      echo "Have a look at the log files $OUTPUT and $ERRORS"
       rm *.fzn
       exit $ret
     fi
   fi
-  echo "$m sucessfully tested!!!"
+  echo "$m processed!"
   echo -e "==========\n"
 done
 rm *.fzn
-rm $OZN
-echo "All went well!!! Test passed."
+rm $OZN $OUT $ERR
+echo "All the examples processed without errors."
+echo "Have a look at the log files $OUTPUT and $ERRORS"
