Ready for new release (?).

diff --git a/test/examples/run_examples b/test/examples/run_examples
--- a/test/examples/run_examples
+++ b/test/examples/run_examples
@@ -35,9 +35,9 @@ do
     then
       echo "Timeout while solving $m!!!"
     else
-	    echo "Error while solving $m!!! Test aborted."
-	    echo "Have a look at the log files $OUTPUT and $ERRORS"
-	    exit $ret
+      echo "Error while solving $m!!! Test aborted."
+      echo "Have a look at the log files $OUTPUT and $ERRORS"
+      exit $ret
     fi
   fi
     
